### ISSUE TITLE
Finer grained control over whether null and missing values are accepted

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#108]
Currently it is possible to prevent a property or element's value from being `null` or missing/`undefined` by assigning the `required` constraint to the item in question in the document definition. But it is not possible to specify only that an item must not be null or that it must not be missing.

This is generally desirable as the default behaviour since many programming languages are incapable of distinguishing between null and missing values. Consider that, in such languages, if a JSON deserializer encounters a missing value, the corresponding property in the resulting object will be null. Furthermore, it is up to a JSON serializer to decide whether to omit a null value (i.e. in the resulting JSON, the property value in question would be missing altogether rather than set to null) or to write it as null. In the face of this uncertainty, it is logical to, by default, favour a definition of "required" that treats null and missing values as equal, as is the case with the `required` constraint.

However, there may be cases where it makes sense to allow a value of `null` but not a missing value or vice versa when expecting documents from client apps written in languages that distinguish between `null` and missing values. For example (not to be considered final):

```
propertyValidators: {
  birthdate: {
    type: 'date',
    // The value may be null, but it must not be missing
    mustNotBeMissing: true
  },
  children: {
    type: 'array',
    arrayElementsValidator: {
      type: 'string',
      // Null values are not allowed in the array
      mustNotBeNull: true
    }
  },
  characteristics: {
    type: 'hashtable',
    hashtableValuesValidator: {
      type: 'integer',
      // Null values are not allowed in the hashtable
      mustNotBeNull: true
    }
  }
}
```

**Comment by dkichler** [comment]
Addressed by #129
