### ISSUE TITLE
Item constraint that requires an exact value match

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#110]
With the introduction of #94 (Support dynamic item validation constraints), it is possible to specify a dynamically computed value for a property or element constraint (e.g. `minimumValue: function(doc, oldDoc, value, oldValue) { ... }`). In some cases, it may be useful to include a constraint that dynamically specifies a value that must be matched _exactly_ by the property/element value.

For example (not to be considered final):

```
propertyValidators: {
  processorId: {
    type: 'string',
    required: true,
    mustEqual: function(doc, oldDoc, value, oldValue) {
      var docIdRegex = /^paymentProcessor\.([A-Za-z0-9_-]+)$/;
      var regexMatches = typeRegex.exec(doc._id);

      return (regexMatches.length > 1) ? regexMatches[1] : '';
    }
  }
}
```

Note that, while the primary use case may be as a dynamic item constraint, it should also accept a static value, as with all other item constraints, for the sake of consistency.

Also note that a constraint value of `null` should be treated literally. In other words, if a `mustEqual` constraint specifies `null`, then the property/element's value must be `null` as well. But a constraint of `undefined` means that the `mustEqual` constraint is not applicable.

**Comment by dkichler** [comment]
Addressed by #125
