### ISSUE TITLE
Backticks in document definitions cause syntax errors

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#113]
Because Sync Gateway uses backticks (&#96;) to denote the beginning and end of multiline strings, any backtick that happens to appear in a document definition will be treated by Sync Gateway as the closing character of the sync function's multiline string, resulting in a syntax error (e.g. "FATAL: Error reading config file config/synctos-test.json: invalid character 'p' after object key:value pair -- rest.ParseCommandLine() at config.go:476") when the sync function is loaded. Therefore, backticks should be replaced with the escape sequence "\\&#96;" when generating a sync function.

**Comment by dkichler** [comment]
Satisfied by #114
