### ISSUE TITLE
Synctos compatibility with sync-gateway-adminui

### ISSUE THREAD

**Issue by shashanktomar** [Kashoo/synctos#120]
Hi Folks,
So after the latest fix, I am able to upload the sync function through admin ui but looks like the admin ui code is completely unstable. 
After adding few docs I refreshed the admin console. It try to rerun the sync-function on page refresh and throws error around immutable fields saying onChange failed because of sync function rejection to update immutable fields. This is weird because i am not even making an update call, I am just refreshing the page. 

How do you guys deploy sync function in production, and how do you test it? Is there a way to stay away from this admin UI console?

**Comment by OldSneerJaw** [comment]
There's not much that synctos can do to deal with glitchy behaviour in the Sync Gateway admin UI. As I noted in issue #116, the admin UI web app does not seem to be well supported by Couchbase at this point. However, based on the description of your problem, it seems likely that the admin UI is automatically creating/updating a document every time the view is loaded, which apparently doesn't play well with synctos' support for immutable documents and fields. If you are determined to use the admin UI, then as an alternative, you might try removing the `immutable`, `cannotReplace` and `cannotDelete` constraints from your document types and instead make each of the affected document types' fields `immutable`, or perhaps better yet, `immutableWhenSet`, to prevent modifications while allowing the admin UI to continue functioning. Alternatively, you might try using curl or [Postman](https://www.getpostman.com/) to construct the [Sync Gateway API](https://developer.couchbase.com/documentation/mobile/1.4/references/sync-gateway/rest-api/index.html) document PUT and DELETE calls.

With regards to testing sync functions generated by synctos, the built in `test-helper` module is the tool of choice. I suggest reading the [Testing](https://github.com/Kashoo/synctos/blob/master/README.md#testing) section of the README for help getting started.

As for deployment, we at Kashoo store our document definitions in a Git repo and we have internal scripts that invoke synctos to generate sync functions from those document definitions and then inject them into a Sync Gateway configuration file. Starting in staging, we perform functional testing on the updated Sync Gateway configuration by exercising our web and mobile apps and then deploy the configuration file to production if that goes well. Every time we need to make changes to our "schema", we modify the underlying document definitions and then repeat the process.

**Comment by shashanktomar** [comment]
Thanks a lot for the explanation @OldSneerJaw.
