### ISSUE TITLE
Immutable constraints that treat null and missing values as different

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#127]
Currently, when a property or element is declared as `immutable`, values that are either `null` or missing/`undefined` are treated as equal to each other. In other words, if a property's value was originally missing and then a new revision attempted to set the same property to `null` (or vice versa), it would be allowed when `immutable` is set to `true` for that property.

This is generally desirable as the default behaviour since many programming languages are incapable of distinguishing between `null` and missing values. Consider that, in such languages, if a JSON deserializer encounters a missing value, the corresponding property in the resulting object will be `null`. Furthermore, it is up to a JSON serializer to decide whether to omit a `null` value (i.e. in the resulting JSON, the property in question would be missing altogether rather than set to `null`) or to write it as `null`. In the face of this uncertainty, it is logical to, by default, favour a definition of immutability that treats `null` and missing values as equal, as is the case with the `immutable` and `immutableWhenSet` constraints.

However, some languages (e.g. JavaScript) are capable of distinguishing between `null` and missing values, so in an attempt to better support them, offer an immutability constraint that treats `null` and missing/`undefined` as different values.

For example (not to be considered final):

```
propertyValidators: {
  foobar: {
    type: 'object',
    immutableStrict: true
  },
  barbaz: {
    type: 'object',
    immutableWhenSetStrict: true
  }
}
```

**Comment by dkichler** [comment]
Satisfied by #132
