### ISSUE TITLE
Equality constraint that treats null and missing values as different

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#128]
Currently, when a property or element is declared with the `mustEqual` constraint, values that are either `null` or missing/`undefined` are treated as equal. In other words, if the `mustEqual` constraint is applied to an item, `a`, of type "object" and the constraint specifies that one of that object's properties, `b` must be `null`, then a document revision where that `a`'s `b` property is missing (or vice versa) would be allowed.

This is generally desirable as the default behaviour since many programming languages are incapable of distinguishing between `null` and missing values. Consider that, in such languages, if a JSON deserializer encounters a missing value, the corresponding property in the resulting object will be `null`. Furthermore, it is up to a JSON serializer to decide whether to omit a `null` value (i.e. in the resulting JSON, the property value in question would be missing altogether rather than set to `null`) or to write it as `null`. In the face of this uncertainty, it is logical to, by default, favour a definition of equality that treats `null` and missing values as equal, as is the case with the `mustEqual` constraint.

However, some languages (e.g. JavaScript) are capable of distinguishing between `null` and missing values, so in an attempt to better support them, offer an equality constraint that treats `null` and missing/`undefined` as different values.

For example (not to be considered final):

```
propertyValidators: {
  foobar: {
    type: 'object',
    mustEqualStrict: {
      foo: 'bar'
      baz: null
    }
  }
}
```

**Comment by dkichler** [comment]
Addressed by #133
