### ISSUE TITLE
Reorganize code in etc directory

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#136]
The project's `etc` directory has become a dumping ground for all JavaScript files that are used indirectly by components in the project. Reorganize so that Node.js modules are defined in the `src` directory and JavaScript templates are defined in the `src/templates` directory. To preserve backward compatibility, leave each module that already exists in the `etc` directory as a simple reference to the corresponding canonical module in the `src` directory.

For example, `etc/test-helper.js`'s content might become

```
module.exports = require('../src/test-helper.js');
```

**Comment by skwoka** [comment]
Addressed by #137.
