### ISSUE TITLE
Include npm version and dependency version badges in README

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#144]
The project's README currently includes badges for Travis CI [build](https://travis-ci.org/Kashoo/synctos) status and [Greenkeeper](https://greenkeeper.io/) status. Add badges that display the current npm package [version](https://badge.fury.io/) and the status of the project's [dependencies and development dependencies](https://david-dm.org/). Also, since the Greenkeeper badge is static and doesn't convey any meaningful info beyond that provided by the dependency badges, remove it.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/145.
