### ISSUE TITLE
Add underscore support

### ISSUE THREAD

**Issue by shashanktomar** [Kashoo/synctos#146]
Syncgateway function supports underscore. Please add the support for it in testHelper and linter.

**Comment by OldSneerJaw** [comment]
Note: For compatibility reasons, the implementation must use Underscore.js [v1.4.4](https://github.com/jashkenas/underscore/tree/484bdb43ec4a9dd6a40e60a2d25317bec7aeb43f) - the version that is bundled with the specific [revision](https://github.com/robertkrimen/otto/tree/5282a5a45ba989692b3ae22f730fa6b9dd67662f/underscore) of the otto JavaScript engine/interpreter used by Sync Gateway 1.x.

**Comment by dkichler** [comment]
Addressed by #168
