### ISSUE TITLE
Access function in testHelper - bad implementation ?

### ISSUE THREAD

**Issue by fijemax** [Kashoo/synctos#147]
Hello,
I use couchbase/syncgateway since a few months.
I writen my own sync function and i would to use synctos to test this function.
In my sync function, i use "access" function with a String and not an Array.

`access("foo", "mission:static:20170721")`
In syncgateway the result user json is : 
```
{
  "name": "foo",
  "all_channels": [
    "!",
    "mission:static:20170721"
  ]
}
```
all_channels is in an array with my new channel access.

I can passed a string or an array to the "access" function.

####################################

Now i created this test for my sync func : 

```
  it('can create a myDocType document', function() {
    var doc = {
      "delivery_date": "2017-07-21T16:22:27.348Z",
      "owner": "foo",
      "type": "mission",
      "_id": "Mission_1534a8de-b412-49bc-97a8-3b535d131406"
    }
   
    testHelper.verifyDocumentCreated(
      doc,
      {
        expectedChannels: 'mission:static:20170721',
        expectedUsers: 'foo' 
      },
      [
        {
          expectedChannels: ['mission:static:20170721'],
          expectedUsers:  ['foo']
        }
      ]);
  });
```

And test fail because testHelper try to compare expectedUsers ARRAY to a STRING.

I think the access function in testHelper could be improve, or I use the test framework badly.

Best regard

**Comment by OldSneerJaw** [comment]
@fijemax: Currently the synctos test-helper module is only designed to work with sync functions that were generated from synctos document definitions configuration. It may be modified at some point in the future to make it more general purpose, but for best results, I suggest you consider re-implementing your sync function using synctos.

**Comment by OldSneerJaw** [comment]
Related to #121.
