### ISSUE TITLE
Permissions for add operations sometimes applied to other operation types

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#149]
There is an edge case in which, if a document definition specifies channel, role or user permissions for the "add" operation, but neglects to include corresponding permissions for either or both of the "replace" or "remove" operations, the generated sync function will allow a user who has the add permission to perform replace or remove operations.

Consider, for example, this case where the document definition specifies a list of general-purpose "write" operation channels and a single special-purpose "add" operation channel:

```javascript
{
  myDocType: {
    typeFilter: simpleTypeFilter,
    channels: {
      write: [ 'write1', 'write2' ],
      add: 'add'
    },
    propertyValidators: { ... }
  }
}
```

If a user belongs to the "add" channel but does not belong to either of the "write1" or "write2" channels, they will still be permitted to execute replace and remove operations, even though they should most certainly not be allowed.

Note: this issue was initially identified by @utekau in pull request #148.

**Comment by dkichler** [comment]
Addressed by #150
