### ISSUE TITLE
Switch assertion library used in specs to Chai

### ISSUE THREAD

**Issue by dkichler** [Kashoo/synctos#157]
It would be nice to support an assertion library that supports custom string feedback for failed assertions.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/158.

**Comment by OldSneerJaw** [comment]
@dkichler: There will likely be more work required for the `1.9.x` branch to be merged into `master`.

**Comment by OldSneerJaw** [comment]
Satisfied by both #158 and #165.
