### ISSUE TITLE
Unable to import document if it was deleted through on sdk

### ISSUE THREAD

**Issue by utekau** [Kashoo/synctos#160]
Hi,
There is critical issue that we encountered today about document deleting. When I delete a document through on java couchbase sdk (bucket.remove()), the document deleted from server successfuly but in sync gateway side, this action doesn't happen. So, when I call all_docs endpoint, it still returns the document but in reality, it doesn't exist. I put the logs below.

> 
> Import+: Attempting to import doc "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44"...
> 
> CRUD+: Doc DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44 is not an SG write, based on cas. cas:150468da9ccf0000 syncCas:"0x00003f1b38680415"
> 
> Import: Created new rev ID 3-5bc670af22d7bdd5d2a60594e9538aad
> CRUD+: Invoking sync on doc "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44" rev 3-5bc670af22d7bdd5d2a60594e9538aad
> 
> CRUD+: No old revision "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44" / "2-816180139d40860fa2d1f39303d4b744"
> 
> CRUD+: No old revision "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44" / "1-5ccb5bf2bfe23d4c5da4dcfcdde8ec7b"
> 
> Sync fn rejected: new=map[_deleted:true _rev:3-5bc670af22d7bdd5d2a60594e9538aad _id:DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44]  old= --> 403 Unknown document type
> 
> CRUD+: Did not update document "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44" w/ xattr: 403 Unknown document type
> 
> Import: Error importing doc "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44": 403 Unknown document type
> 
> WARNING: Unable to import doc "DocumentLibraryFileAttacher::484018fa-2c61-4298-922e-923e4b63ce44" - external update will not be accessible via Sync Gateway.  Reason: 403 Unknown document type -- db.(*changeCache).DocChangedSynchronous() at change_cache.go:394
> 

As you can see, the sync gateway rejects the update and inconsistency occurs. For a deleted document, it  tries to get type from that.

Note: Most probably, this problem might happen when you delete a document from couchbase web panel.

Thanks.

**Comment by OldSneerJaw** [comment]
@utekau: To be clear, before we investigate further, you are using Couchbase Server 5.0.x and Sync Gateway 1.5.x with [bucket sharing](https://developer.couchbase.com/documentation/mobile/1.5/guides/sync-gateway/shared-bucket-access.html#how-to-enable-it) **explicitly enabled** in the Sync Gateway configuration file for the bucket/database in question?

**Comment by utekau** [comment]
Hi @OldSneerJaw,
As you said we are using those versions (not the beta ones). And we set "enable_shared_bucket_access" property to true.

**Comment by dkichler** [comment]
Addressed by #162
