### ISSUE TITLE
Embed simple-mock as a static development dependency

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#163]
The test-helper module currently has a single external development dependency (simple-mock) which makes it awkward for use as a dependency in another project that needs to write test cases for its synctos document definitions. Embed simple-mock as a static dependency so it can be used by the test-helper module but is not required by its dependents.

Relates to #157, in that it removes the last remaining external dependency for using the test-helper module (the previous being expect.js which was replaced with Node.js Assert).

**Comment by dkichler** [comment]
Satisfied by #164
