### ISSUE TITLE
Option to combine add, replace and remove channels into a single "write" channel definition

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#17]
Currently it is necessary to specify the channel(s) for the `add`, `replace` and `remove` operations individually, even if they are all the same value. Provide support for a single `write` parameter in the document `channels` object that is then applied to any of the operations in question.

For example, instead of

    channels: {
      view: 'my-view-channel',
      add: 'my-write-channel',
      replace: 'my-write-channel',
      remove: 'my-write-channel'
    }

allow the following:

    channels: {
      view: 'my-view-channel',
      write: 'my-write-channel'
    }

The name of the parameter is subject to debate.

**Comment by ziemek** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/18.
