### ISSUE TITLE
Reorganize project source structure

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#174]
- Create a `src/index.js` and make it the main module for the package (overrides issue #123). It should export properties for the `test-helper` module and `sync-function-loader` modules at least. This will allow dependents to import the `test-helper` module with `require('synctos').testHelper` instead of `require('../node_modules/synctos/src/test-helper.js')`.
- Move sync function/document definition template files from `src/templates` to `templates`. The `src` directory (and any future subdirectories) should only contain Node.js code.
- Move specs for Node.js code into the `src` directory so they live beside the code they're testing. Specs for template code should remain where they are in the `test` directory to serve as a repository of test-helper module examples for end users.

**Comment by ziemek** [comment]
Addressed by the above PRs.
