### ISSUE TITLE
UUID data validation type

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#176]
Add a new validation type for [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier)-format strings.

Note that UUIDs can contain either uppercase or lowercase letters. The UUID strings "db8c4e96-594a-4713-8e2e-aa6f03e71b3b", "DB8C4E96-594A-4713-8E2E-AA6F03E71B3B" and "dB8c4E96-594a-4713-8E2e-Aa6F03e71B3b" are all valid but they need not be considered equal to each other by the various `mustEqual` and `immutable` constraints.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/179.
