### ISSUE TITLE
Data validation type for time of day

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#180]
The `datetime` and `date` validation types already support ISO 8601 dates with and without time and time zone components, respectively. Add a new validation type (e.g. `time` or `timeOfDay`) that represents the time of day without a date or time zone component. Support should conform to the [ECMAScript simplified ISO 8601](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) standard for time.

**Comment by dkichler** [comment]
addressed by #201
