### ISSUE TITLE
Provide a code coverage report for tests

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#181]
Using a utility like [nyc](https://www.npmjs.com/package/nyc), generate a code coverage report whenever the project's test suite is executed. Only code from the `src` directory (i.e. only Node.js code; not template code) should be included in the coverage report. Ensure that statements and branches have at least 95% coverage and functions have 100% coverage.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/184.
