### ISSUE TITLE
Upgrade minimum supported Node.js version to latest Long Term Support release

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#185]
Set the minimum Node.js version to the latest version of the current [Long Term Support](https://github.com/nodejs/Release#release-schedule) release (e.g. v8.9.4 at the time of writing). This will open the possibility to use a variety of ECMAScript 2015+ features without fear that it will not work on all supported Node.js versions. Be sure to update the [engines](https://docs.npmjs.com/files/package.json#engines) section of `package.json` and to set the JSHint `esversion` option to `6`.

**NOTE**: This is a breaking change. It should be undertaken only in concert with other breaking changes.

**Comment by dkichler** [comment]
addressed by #220
