### ISSUE TITLE
JavaScript error when mustEqual constraint is violated

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#190]
When the `mustEqual` or `mustEqualStrict` constraints are violated, Sync Gateway responds with a 500 Internal Server Error:

```
{
    "error": "Internal Server Error",
    "reason": "Exception in JS sync function"
}
```

It appears to be because the constraints in question attempt to use `JSON.stringify` to format the error message, but the `JSON` global object is not supported by Sync Gateway.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/191.
