### ISSUE TITLE
Date-time validation type supports invalid time components

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#196]
The ECMAScript [Date Time String Format](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) documentation describes the expected date-time format for JavaScript Date objects. The regular expression used to test values of the `datetime` validation type does not conform and thus allows date-time strings that are not supported by Sync Gateway's JavaScript interpreter.

Specifically:
- The use of a comma as the decimal separator between seconds and milliseconds is not officially supported
- A time zone of "z" (as opposed to "Z") is not officially supported
- The minutes component of a time zone designator (e.g. the ":00" part of "-08:00") is not officially optional
- The use of a blank space (as opposed to "T") to separate the date and time components is not officially supported
- The minutes part of the time component is not officially optional

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/198.
