### ISSUE TITLE
Make month and day components of date validation type optional

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#197]
Currently the `date` validation type requires that candidate values have year, month and day components (e.g. "2018-02-03"), but the ECMAScript specification for [Date Time String Format](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) indicates that both the month and day components are optional (e.g. "2018-02", "2018"). Update the `date` validation type to allow these components to be omitted, with assumed values of `01` in either case. Care must be taken to ensure that "2018-01-01", "2018-01" and "2018" are considered equal to each other with regards to the `minimumValue`, `minimumValueExclusive`, `maximumValue` and `maximumValueExclusive` constraints.

**Comment by dkichler** [comment]
Addressed by #218
