### ISSUE TITLE
Date and date-time validation types permit dates that are invalid

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#199]
The `date` and `datetime` validation types incorrectly allow candidate values that do not represent valid dates. For example, if a candidate value of "2018-02-29T12:27:53.991-0800" is received, the value will be allowed even though there is no February 29th in 2018 (it's not a leap year). Ensure that a candidate `date` or `datetime` value can be parsed by the built in `Date` object before accepting it.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/200.
