### ISSUE TITLE
Date range validation fails for values far in the past or future

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#203]
Dates after "2262-04-11T23:47:16.854Z" and before "1677-09-21T00:12:43.146Z" foil the `maximumValue`/`maximumValueExclusive` and `minimumValue`/`minimumValueExclusive` constraints, respectively, of the `date` and `datetime` validation types. For example, suppose a `datetime` property has a `maximumValue` or `maximumValueExclusive` constraint of "2018-02-05T00:00:00.000-0800"; if the sync function receives a candidate value of "2262-04-11T23:47:16.855Z" or higher, it will allow the value even though it is clearly after than the maximum value. Similarly, if a `datetime` property has a `minimumValue` or `minimumValueExclusive` constraint of "2018-02-04T00:00:00.000-0800" and the sync function receives a candidate value of "1677-09-21T00:12:43.145Z" or lower, it will erroneously allow the value.

The issue seems to be a result of buggy parsing of ISO 8601 date strings by the `Date` constructor and `Date.parse` function from the JavaScript engine that is used by Sync Gateway ([otto](https://github.com/robertkrimen/otto)). If either encounters an ISO 8601 date that falls outside the range, it produces a value that is incorrect. For example, parsing "2262-04-11T23:47:16.855Z" produces "1677-09-21T00:12:43.146Z".

**Comment by dkichler** [comment]
Addressed by #222
