### ISSUE TITLE
Constraint that requires string values to be trimmed

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#204]
Add a new `string` validation type constraint that rejects values that begin and/or end with whitespace (e.g. `mustBeTrimmed`). In other words, values for properties/elements with this constraint enabled must be trimmed before saving to the database. Should default to a value of `false`.

**Comment by dkichler** [comment]
Addressed by #213

**Comment by dkichler** [comment]
In fact, #213 addresses a _different_ issue (#212)

**Comment by dkichler** [comment]
_actually_ addressed by #211
