### ISSUE TITLE
Ignore all top-level document properties that start with an underscore

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#207]
Sync Gateway prohibits the use of top-level document key names that start with an underscore because it reserves the right to use them for internal properties. The synctos validation module whitelists `_id`, `_rev`, `_deleted`, `_revisions` and `_attachments` when they are at the top level of a candidate document since they are internal properties, but it should whitelist _all_ properties that start with an underscore at the top level of a candidate document to provide forward compatibility in case additional internal properties are introduced in the future.

**Comment by dkichler** [comment]
Addressed by #210
