### ISSUE TITLE
Allow document definition fragments to be nested

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#215]
Document definition modularity using the `importDocumentDefinitionFragment` macro was originally implemented for issue #66. Modify the implementation to recursively import document definition fragments/modules so that they can be embedded an arbitrary number of levels deep. As it is currently, only the top level document definition file can import a file fragment.

For example, suppose document definitions file `a.js` has the following contents:

```javascript
{
  typeFilter: ...,
  channels: ...,
  propertyValidators: {
    propertyB: importDocumentDefinitionFragment('b.js')
  }
}
```

And file `b.js` has the following contents:

```javascript
{
  type: 'object',
  propertyValidators: {
    propertyC: importDocumentDefinitionFragment('c.js')
  }
}
```

And file `c.js` has the following contents:

```javascript
{ type: 'string' }
```

Then the complete document definitions should look like this:

```javascript
{
  typeFilter: ...,
  channels: ...,
  propertyValidators: {
    propertyB: {
      type: 'object',
      propertyValidators: {
        propertyC: { type: 'string' }
      }
    }
  }
}
```

**Comment by dkichler** [comment]
Addressed by #216
