### ISSUE TITLE
Modularize the sync function validation module

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#217]
The `sync-function-validation-module.js` file has become unwieldy as additional validation logic has been bolted on to it over time. Break it up into smaller modules to help with readability and maintainability of the code.

Suggested modules:
- Date and time validation
- Attachment validation
- Simple type (e.g. string, integer, float, boolean) validation
- Complex type (e.g. array, hashtable, object) validation
- Equality validation
- Range validation

Related to issue #215.

**Comment by dkichler** [comment]
Addressed by #239

**Comment by OldSneerJaw** [comment]
There's still more work to be done.

**Comment by dkichler** [comment]
Addressed by #239, #241 and #242
