### ISSUE TITLE
Support document authorization by role

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#22]
Currently document type definitions are limited to providing a list of channels to which a user must belong (either directly or indirectly through membership in a role that includes the channel(s)) in order to create/replace/delete documents of that type. However, Sync Gateway also exposes the `requireRole` function to sync functions, which specifies that the user must belong to one of the roles provided. Add configuration support for defining the list of roles that a document requires.

See [Authorizing Document Updates](http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/channels/developing/index.html#authorizing-document-updates) for more info. Related to #23.

**Comment by dkichler** [comment]
This has been satisfied by #57
