### ISSUE TITLE
Upgrade Node.js modules to ECMAScript 2015 specification

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#221]
An incomplete list of things to address within the `src` and `test` directories to upgrade to ES2015:
* Replace `var`s with [`const`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const) (preferred) and [`let`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let) (when unavoidable)
* Replace anonymous functions with [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
* Replace concatenated strings with [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
* Replace `for` loops with [`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) loops or [array iteration methods](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Iteration_methods)
* Replace manual copying of arrays with the [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator)
* Use shorthand for object property assignment (e.g. replace `{ foo: foo, bar: bar }` with `{ foo, bar }`)
* Use object destructuring for Node.js `require` calls (e.g. replace `const expect = require('chai').expect;` with `const { expect } = require('chai');`)

**Comment by dkichler** [comment]
Addressed by #233

**Comment by OldSneerJaw** [comment]
Not ready to be closed yet. The `test` directory is still to be upgraded to ES2015.

**Comment by dkichler** [comment]
Addressed by #233 & #240
