### ISSUE TITLE
Use intelligent equality comparisons for specialized string types

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#225]
Several validation types (e.g. `date`, `datetime`, `time`, `timezone`, `uuid`) are specialized strings with additional meaning encoded within them; however, comparisons by way of the `mustEqual` constraint are performed with a simple strict equality (`===`) operator that doesn't take into account that two different strings of these specialized types can represent the same value. For example, the values of "2018-02-11" (midnight UTC because the time component is missing) and "2018-02-10T16:00:00.000-08:00" represent the same point in time and should thus be considered equal by the `mustEqual` constraint when encountered on a validation type of `datetime`.

The `mustEqualStrict` constraint should continue to use strict equality for all simple validation types.

Related to issue #227.

**Comment by dkichler** [comment]
Addressed by #228
