### ISSUE TITLE
Use intelligent immutability comparisons for specialized string types

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#227]
Several validation types (e.g. `date`, `datetime`, `time`, `timezone`, `uuid`) are specialized strings with additional meaning encoded within them; however, comparisons by way of the `immutable` and `immutableWhenSet` constraints are performed with a simple strict equality (`===`) operator that doesn't take into account that two different strings of these specialized types can represent the same value. For example, the values of "bd851433-e816-4d4d-9a46-1a5c4711db3a" and "BD851433-E816-4D4D-9A46-1A5C4711DB3A" represent the same universally unique identifier (they differ only by case) and should thus be considered equal by the immutability constraints when encountered on a validation type of `uuid`.

The `immutableStrict` and `immutableWhenSetStrict` constraints should continue to use strict equality for all simple validation types.

Related to issue #225.

**Comment by dkichler** [comment]
Addressed by #229
