### ISSUE TITLE
Support document authorization by specific users

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#23]
Currently document type definitions are limited to providing a list of channels to which a user must belong (either directly or indirectly through membership in a role that includes the channel(s)) in order to create/replace/delete documents of that type. However, Sync Gateway also exposes the `requireUser` function to sync functions, which specifies that only one of the provided users may perform the operation. Add configuration support for defining the list of users that a document requires.

See [Authorizing Document Updates](http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/channels/developing/index.html#authorizing-document-updates) for more info. Related to #22.

**Comment by dkichler** [comment]
Addressed by #58
