### ISSUE TITLE
Support dynamic assignment of channels to roles and users

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#24]
Sync Gateway exposes the `access` function to sync functions, which allows channels to be assigned to users and roles on the fly ([more info](http://developer.couchbase.com/documentation/mobile/current/develop/guides/sync-gateway/channels/developing/index.html#programmatic-authorization)). Add support for document definitions to supply configuration that is applied after the user is authorized (i.e. via the `requireAccess` function) and the document's contents pass validation, but before channels are assigned (i.e. via the `channel` function).

For example (not to be considered final):

```
myDocType: {
  channels: ...,
  typeFilter: ...,
  propertyValidators: ...,
  accessAssignments: [
    {
      users: function(doc, oldDoc) {
        return doc.members;
      },
      roles: function(doc, oldDoc) {
        return doc.groups;
      },
      channels: function(doc, oldDoc) {
        return doc.channels;
      }
    },
    {
      users: [ 'user1' ],
      roles: [ 'admins', 'power-users' ],
      channels: 'channel1'
    }
  ]
},
```

**Comment by dkichler** [comment]
This issue was sufficiently addressed by #51
