### ISSUE TITLE
The test-helper module incorrectly represents an old document that does not exist as undefined

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#243]
When a brand new document is in the process of being created, Sync Gateway passes a value of `null` as the second argument to the sync function (e.g. the `oldDoc` parameter). However, the test-helper module's `verifyDocumentCreated` and `verifyDocumentNotCreated` functions pass `undefined` as the second parameter, which is obviously inconsistent with reality. Update the test-helper module to always provide a value of `null` to represent the case where a previous revision for the document does not exist.

**Comment by skwoka** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/244.
