### ISSUE TITLE
Allow a document with an unknown type to be deleted via the admin API

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#250]
As document definitions evolve over time, a document type may be subsequently removed, effectively "orphaning" a document of that type since no one, not even when using the Sync Gateway [admin API](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/authorizing-users/index.html#admin-access), will be able to delete it at that point. Ensure that such documents can be deleted via the admin API.

**Comment by skwoka** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/251.
