### ISSUE TITLE
Provide default type filter function

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#26]
Because many/most document types are likely to use a type filter function that determines the type by simply matching the value of the document's `type` property, provide a default function (e.g. `defaultTypeFilter`) that checks that the `type` property's value exactly matches the document type name (the key that identifies the document in the document definitions object).

For example,

```
myDocType: {
  channels: ...,
  propertyValidators: ...,
  typeFilter: simpleTypeFilter
}
```

would return `true` if a candidate document's `type` property is "myDocType".

**Comment by dkichler** [comment]
👍 Good to go with #27
