### ISSUE TITLE
JavaScript error on document write in Sync Gateway 1.x

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#270]
# Bug Report

## Steps to reproduce

1. Generate a sync function from document definitions (e.g. `./make-sync-function -j test/resources/date-doc-definitions.js build/example-sync-function.txt`)
2. Copy and paste the sync function into a Sync Gateway configuration file
3. Launch Sync Gateway 1.x with the Sync Gateway configuration file (e.g. `bin/sync_gateway /path/to/sync-gateway-config.json`)
4. Add, replace or delete a document. For example:

```
PUT /test/dateDoc HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
    "formatValidationProp": "2016-07-17"
}
```

## Actual behaviour

The server responds with a status of 500 Internal Server Error and the following body:

```
{
    "error": "Internal Server Error",
    "reason": "Exception in JS sync function"
}
```

## Expected behaviour

The server should respond with a status of 201 Created if the document does not already exist.

## Environment

* Synctos: 2.2.0
* Couchbase Server: any
* Sync Gateway: 1.5.1
* Operating system: any

**Comment by dkichler** [comment]
Addressed by #271
