### ISSUE TITLE
Date range validation is incorrect for dates between years 0 and 99

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#276]
# Bug Report

## Steps to reproduce

Example document definitions configuration:

```javascript
{
  myDocType: {
    typeFilter: simpleTypeFilter,
    channels: { write: '!' }, // Allows all users to add, replace or remove docs of this type
    propertyValidators: {
      date: {
        type: 'date',
        minimumValue: '1900-01-01'
      }
    }
  }
}
```

1. Generate a sync function from the example document definitions above (e.g. `./make-sync-function -j /path/to/example-doc-definitions.js build/example-sync-function.txt`)
2. Copy and paste the generated sync function into a Sync Gateway configuration file
3. Launch Sync Gateway with the Sync Gateway configuration file (e.g. `bin/sync_gateway /path/to/sync-gateway-config.json`)
4. Add a new document with a year between 0 and 99. For example:

```
PUT /test/year-bug-test-1 HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
    "type": "myDocType",
    "date": "0097-07-17"
}
```

## Actual behaviour

The document is created and Sync Gateway responds with 201 Created because a year between 0 and 99 is interpreted as a year between 1900 and 1999 ([more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Two_digit_years_map_to_1900_-_1999)).

## Expected behaviour

The document should be rejected because the date's year is less than the minimum year of 1900.

## Environment

* Synctos: 2.2.1
* Couchbase Server: 5.0.1 CE
* Sync Gateway: 1.5.1
* Operating system: macOS High Sierra

**Comment by dkichler** [comment]
Addressed by #277
