### ISSUE TITLE
Extended year format in date strings

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#278]
# Feature Request

## Description

The ECMAScript simplified ISO 8601 date-time string specification includes support for signed six-digit [extended years](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15.1). Currently only four-digit years are supported. Enhance the `date` and `datetime` validation types to support extended years according to ES5.

## Examples

Some date strings that should be accepted:

- -270999-03-21T15:00:59.008Z
- +060964-11-05T06:53:16.366Z
- +000000-01-01T00:00Z
- -012345-02-22

**Comment by dkichler** [comment]
Addressed by #283
