### ISSUE TITLE
Discard the customActionStub for testing of custom actions

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#279]
# Task

## Description

The `customActionStub` is a function that is part of the test helper/test fixture environment to facilitate testing of custom actions (e.g. `onAuthorizationSucceeded`, `onValidationSucceeded`, `onAccessAssignmentsSucceeded`, etc.). However, this is an inelegant solution that makes it difficult to provide proper verification that custom action metadata is assigned by the correct sync function lifecycle events. A more robust approach has been demonstrated by the [couchster](https://github.com/OldSneerJaw/couchster) spin-off project: have the custom action function halt execution of the sync function altogether and provide an object with the complete state that was passed to the custom action function for validation by the test module.

## Examples

See [custom-actions.spec.js](https://github.com/OldSneerJaw/couchster/blob/beab45f97d6580196e055e316bac963b5c5a66cf/test/custom-actions.spec.js) and [custom-actions-doc-definitions.js](https://github.com/OldSneerJaw/couchster/blob/beab45f97d6580196e055e316bac963b5c5a66cf/test/resources/custom-actions-doc-definitions.js) from the couchster repo.

**Comment by dkichler** [comment]
Satisfied by #280
