### ISSUE TITLE
Parameter to allow unknown properties in a document or object

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#28]
Currently sync functions do not allow root-level properties that are not explicitly declared in the document definition. The same is true of objects nested within a document that declare a `propertyValidators` parameter. Add an optional parameter (e.g. `allowUnknownProperties`) to these components that, when enabled on a document, allows a document to include root-level properties that are not explicitly declared in the document definition and, when enabled on a nested object, allows unknown properties on that level of the object graph. Should be disabled by default.

**Comment by dkichler** [comment]
#48 has been merged, which satisfies this issue
