### ISSUE TITLE
Support hour 24 in date and time validation types

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#282]
# Feature Request

## Description

The ECMAScript specification's [Date Time String Format](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) specifies that implementers support midnight specified as either hour zero or hour 24. Update both the `datetime` and `time` validation types to allow hour 24 and to treat it as equivalent to midnight on the following day. Ensure that hour 24 is only valid if the minutes, seconds and milliseconds components of the string are all zero. In the case of the `time` validation type, hour 0 and hour 24 should not be considered semantically equal to each other by way of the `mustEqual` and `immutable`/`immutableWhenSet` constraints.

## Examples

Date-time strings that should be considered valid and semantically equal to each other:

- `2018-04-03T00:00Z`
- `2018-04-03T00:00:00.000Z`
- `2018-04-03T00:00:00Z`
- `2018-04-02T24:00Z`
- `2018-04-02T24:00:00Z`
- `2018-04-02T24:00:00.000Z`

And some time strings that should be considered valid but hours 0 and 24 are not semantically equal to each other:

- `00:00`
- `00:00:00`
- `00:00:00.000`
- `24:00`
- `24:00:00`
- `24:00:00.000`

**Comment by dkichler** [comment]
Addressed by #291
