### ISSUE TITLE
Throw an Error object when there is an authorization or validation failure

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#285]
# Feature Request

## Description

Currently, when a generated sync function throws an authorization or validation error, it does so as a plain object as [suggested](https://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/sync-function-api-guide/index.html#throw) by the official Couchbase developer docs. For example:

```javascript
throw { forbidden: 'missing channel access' };
```

While this is technically valid JavaScript, it produces a less desirable result when using the test-fixture-maker module to validate document definitions. Specifically, mocha generates a message that can be a little confusing/misleading if an unexpected validation error occurs in a test case. For example:

```
Error: the object {
  "forbidden": "Invalid hashtableDoc document: hashtable \"staticSizeValidationProp\" must not be smaller than 3 elements"
} was thrown, throw an Error :)
```

Despite being a cheerful reminder that it is preferable to throw an Error object, the message can be confusing to the user since they may not be aware of that implementation detail. Instead, sync functions should throw an Error object with its `forbidden` property set accordingly in such instances.

## Examples

```javascript
var errorMessage = 'missing channel access';
var error = new Error(errorMessage);
error.forbidden = errorMessage;

throw error;
```

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/286.
