### ISSUE TITLE
Backticks are escaped even if sync function is not written to a file

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#288]
# Bug Report

The sync-function-loader module automatically escapes all occurrences of the backtick character as it is reading the document definitions. This is so that the generated sync function can be inserted into a Sync Gateway configuration file where the backtick character is used to denote a multi-line string. However, this could be problematic for a caller of the sync-function-loader module's `load` method if, for example, they need to perform some sort of processing on the generated sync function string before manually writing it to a file or they'd like to run it in their own Node.js [VM](https://nodejs.org/dist/latest-v8.x/docs/api/vm.html). While certainly an edge case, it is still worth addressing.

## Steps to reproduce

Consider if the following expression were to appear in a document definitions file:

```
originalString.replace(/\\\`/g, () => '`')
```

## Actual behaviour

When read by the sync-function-loader, the expression would become

```
originalString.replace(/\\\\`/g, () => '\`')
```

which would match the wrong substring.

## Expected behaviour

The expression should be read verbatim:

```
originalString.replace(/\\\`/g, () => '`')
```

Backticks in the document definitions should only be escaped at the point that they are written to a file.

## Environment

* Synctos: 2.2.1
* Couchbase Server: 5.5 Developer Build
* Sync Gateway: 1.5.1
* Operating system: macOS High Sierra

**Comment by dkichler** [comment]
Satisfied by #290
