### ISSUE TITLE
Refactor common logic from test-environment-maker and validation-environment-maker modules

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#289]
# Task

## Description

The test-environment-maker and validation-environment-maker modules are functionally identical except that they use different template files and they expect different placeholder/macro name strings. Extract the common functionality from each and combine them into a single module with those two options as parameters of the `init` function.

## Examples

The new module's `init` function would be called like so:

```
const templatePath = path.resolve(__dirname, '../../templates/environments/validation-environment-template.js');
const macroName = '$DOC_DEFINITIONS_PLACEHOLDER$';
const env = environmentMaker.init(templatePath, macroName, rawDocDefinitionsString, docDefinitionsFilename);
```

**Comment by dkichler** [comment]
Satisfied by #310
