### ISSUE TITLE
Parameter to indicate that an item cannot be modified if it has a value

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#29]
Similar to the `immutable` constraint on items, such a constraint (e.g. `immutableIfSet`) would only prevent modifications to properties and elements that already have a value assigned. In other words, the value of an item that is protected by this constraint can only be set if it is currently `undefined` (or perhaps `null` as well?). Does not apply to documents.

**Comment by ziemek** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/38.
