### ISSUE TITLE
Permanent workaround for bugs in Date object implementation

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#292]
# Feature Request

## Description

The Sync Gateway 2.0.0 betas have introduced additional bugs in the `Date` object's handling of dates after "2262-04-11T23:47:16.854Z" and before "1677-09-21T00:12:43.146Z". The bug has been reported to the Sync Gateway project maintainers (https://github.com/couchbase/sync_gateway/issues/3426) and to the maintainers of the otto JavaScript engine (https://github.com/robertkrimen/otto/issues/302). To limit the impact of this bug on synctos clients that make use of the `date` and `datetime` validation types' comparison constraints (e.g. `maximumValue`, `minimumValue`, `mustEqual`, `immutable`, etc.), introduce a permanent workaround that completely eliminates reliance on the `Date` object for such comparisons.

These issues appear to be a more severe version of an issue that was addressed in a previous release of synctos: #203.

**Comment by dkichler** [comment]
Addressed by #297
