### ISSUE TITLE
Time zones incorrectly allow the colon to be omitted

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#294]
# Bug Report

## Steps to reproduce

1. Generate a sync function from the `datetime-doc-definitions.js` file: `./make-sync-function -j test/resources/datetime-doc-definitions.js build/output.txt`
2. Insert the generated sync function into a Sync Gateway configuration file
3. Create a document with a date-time that has no colon separating hours and minutes in the time zone component. For example:

```
PUT /test/datetimeDoc HTTP/1.1
Host: localhost:4985
Content-Type: application/json

{
	"formatValidationProp": "2016-07T15:20:09.348-0700"
}
```

## Actual behaviour

The document will be accepted even though the ECMAScript specification for [Date Time String Format](https://www.ecma-international.org/ecma-262/5.1/#sec-15.9.1.15) does not allow omission of the colon that should separate the hours and minutes of the time zone.

## Expected behaviour

The document should be rejected with a status of 403 Forbidden and the reason "Invalid datetimeDoc document: item \\"formatValidationProp\\" must be an ECMAScript simplified ISO 8601 date string with optional time and time zone components".

## Environment

* Synctos: 2.2.1
* Couchbase Server: 5.5 Developer Build
* Sync Gateway: 2.0.0 Beta 2
* Operating system: macOS High Sierra

**Comment by dkichler** [comment]
Addressed by #296
