### ISSUE TITLE
Decompose the document validation module into separate submodules

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#305]
# Task

## Description

Break down the `validation-module.js` file into two separate submodules to improve code readability and maintainability: one for validating general constraints on a document (e.g. `cannotReplace`, `cannotDelete`, `documentIdRegexPattern`) and one for validating a document's properties.

## Examples

* `document-constraints-validation-module.js`: for top-level document constraints
* `document-properties-validation-module.js`: for properties within a document

**Comment by dkichler** [comment]
Satisfied by #308
