### ISSUE TITLE
Case insensitive equality constraint for strings

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#311]
# Feature Request

## Description

Provide a new constraint for the `string` validation type that checks for equality while ignoring differences in case.

## Examples

```javascript
myStringProp: {
  type: 'string',
  mustEqualIgnoreCase: function(doc, oldDoc, value, oldValue) {
    return doc.aProp + '-' + doc.bProp;
  }
}
```

**Comment by dkichler** [comment]
Addressed by #312
