### ISSUE TITLE
Support an ambiguously typed property validator

### ISSUE THREAD

**Issue by dkichler** [Kashoo/synctos#318]
## Description

It would be useful to be able to define an ambiguously types property validator.  The use case being a required property whose type is dependent/inferred from another property on the document.  Currently `type` is a required property on a property validator, and the only way to allow an ambiguously typed property is to omit defining it at all and instead mark the parent `object` validator with `allowUnknownProperties`.  This leaves no means by which to mark the field in question as required, and the resulting sync function will accept objects lacking that property. 

## Examples

Consider an example where dynamic `type` on a property validator is not sufficient:

```
suggestions: {
  type: 'array',
  required: true,
  arrayElementsValidator: {
    type: 'object',
    required: true,
    propertyValidators: {
      // Name of the field the suggestion is intended for.  Field name should imply expected value type.
      suggestedField: {
        type: 'enum',
        predefinedValues: [ 'accountNumber', 'taxIds' ],
        required: true
      },
      // Value of the suggestion
      suggestedValue: {
        type: function(doc, oldDoc, value, oldValue) {
          // no simple way to access the sibling property suggestedField, which implies type
        },
        required: true
      }
    }
  }
}
```

**Comment by dkichler** [comment]
This use case would be satisfied if the dynamic `type` constraint function of a property validator had access to the stack of properties being validated (and therefor providing access to sibling and even parent object properties)

**Comment by OldSneerJaw** [comment]
I believe this specific use case can be handled by the current version of synctos by instead defining the nested `propertyValidators` property as a function. For example:

```javascript
suggestions: {
  type: 'array',
  required: true,
  arrayElementsValidator: {
    type: 'object',
    required: true,
    propertyValidators: function(doc, oldDoc, value, oldValue) {
      return {
        // Name of the field the suggestion is intended for.  Field name should imply expected value type.
        suggestedField: {
          type: 'enum',
          predefinedValues: [ 'accountNumber', 'taxIds' ],
          required: true
        },
        // Value of the suggestion
        suggestedValue: {
          type: value.suggestedField === 'accountNumber' ? 'string' : 'array',
          required: true
        }
      };
    }
  }
}
```

**Comment by dkichler** [comment]
That does indeed cover my use case
