### ISSUE TITLE
Range validation parameters that exclude the minimum/maximum values

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#32]
The `minimumValue` and `maximumValue` constraints limit the range of values that can be assigned to items of `integer`, `float`, `date` and `datetime` types. However, the minimum and maximum values are inclusive, which can be problematic for floating point numbers where, for example, you might want to ensure that all values are less than 7.5. What do you use as the maximum (inclusive) value? 7.49? 7.499999?

Instead, introduce new constraints (e.g. `minimumValueExclusive`, `maximumValueExclusive`) for these data validation types where the minimum and maximum values are exclusive rather than inclusive.

**Comment by ziemek** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/45.
