### ISSUE TITLE
Option to ignore item validation errors when value is unchanged

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#323]
# Feature Request

## Description

Occasionally, when updating document definitions, it is necessary to introduce a breaking change to the schema. However, if there are already documents in the database that conform to the old schema but not the new schema (e.g. a `string`'s `regexPattern` or an `integer`'s `minimumValue` have changed), this can require a full, complicated data migration to the new format that may result in revision conflicts if any of the documents in question also happen to have been modified by an offline client. Sometimes this is unavoidable, but in other cases it is acceptable to "grandfather" the old value in for existing documents (e.g. a product ID format that is no longer used for new products, but is still valid for old, obsolete products).

This feature would introduce a new [universal item validation constraint](https://github.com/Kashoo/synctos/blob/master/README.md#universal-constraint-validation) (e.g. `skipValidationWhenValueUnchanged`) that suppresses validation errors for that property/element when replacing a document revision where the corresponding property/element has the same semantic value. Also introduce a constraint that requires strict equality (e.g. `skipValidationWhenValueUnchangedStrict`).

## Examples

Consider the following document definition:

```javascript
myDoc: {
  typeFilter: simpleTypeFilter,
  channels: { write: 'write' },
  propertyValidators: {
    code: {
      type: 'string',
      regexPattern: /^[a-z]{4}-\d{3}$/,
      skipValidationWhenValueUnchanged: true
    },
    quantity: {
      type: 'integer',
      required: true,
      minimumValue: 0
    }
  }
}
```

The `code` property must be four lowercase letters, followed by a dash and _three_ digits. However, if the previous version of the `code` property's `regexPattern` expected only two digits at the end, then values from existing documents that match that regular expression would be invalid if not for the `skipValidationWhenValueUnchanged` option.

Therefore with a previous document body of `{ "code": "abcd-12", "quantity": 5 }`, the following new document revision would be considered valid even though it validates the updated `regexPattern` for `code`: `{ "code": "abcd-12", "quantity": 4 }`

**Comment by dkichler** [comment]
Satisfied by #325 and #326
