### ISSUE TITLE
Validation type that accepts any type of value

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#324]
# Feature Request

## Description

A new validation type (e.g. `type: 'any'`) that allows the property/element's value to be any of the following JSON types: number, string, boolean, array, object. Should support all of the [universal item validation constraints](https://github.com/Kashoo/synctos/blob/master/README.md#universal-constraint-validation), but it is not necessary to support type-specific validation constraints (e.g. `string`'s `regexPattern`, `array`'s `maximumLength`, `hashtable`'s `minimumSize`). May be especially useful for array and hashtable element validators where either contains an arbitrary mix of types.

## Examples

Consider the following example document definition:

```javascript
{
  myDoc: {
    typeFilter: simpleTypeFilter,
    channels: { write: 'write' },
    propertyValidators: {
      entities: {
        type: 'array',
        arrayElementsValidator: {
          type: 'any',
          required: true,
          immutable: true
        }
      }
    }
  }
}
```

The following document body would pass validation:

```json
{
  "entities": [
    "foo",
    -32.7,
    "bar",
    { "baz": true }
  ]
}
```

**Comment by dkichler** [comment]
Addressed by #327
