### ISSUE TITLE
Support the requireAdmin function in test fixtures

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#331]
# Feature Request

## Description

The release of Sync Gateway 2.1 included a new addition to the sync function API: [`requireAdmin`](https://github.com/couchbase/sync_gateway/issues/3276). Update the test-fixture-maker module to support `requireAdmin` so that tests can be written for document definitions that make use of it in custom actions.

## Examples

```javascript
customActions: {
  onValidationSucceeded: function(doc, oldDoc, customActionMetadata) {
    if (doc.x === 'foobar') {
      requireAdmin();
    }
  }
```

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/333.
