### ISSUE TITLE
Does not return a non-zero exit status when sync function generation fails

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#36]
The `make-sync-function` script returns an exit status of zero in all cases, even if the script failed (e.g. because the document definitions file does not exist). It should return a non-zero exit status in failure cases.

To reproduce the issue, execute the following commands:

    $ ./make-sync-function /path/to/file-that-does-not-exist.js /path/to/generated-sync-function.js
    $ echo $?

The second command displays the exit status from the previous command. It should be non-zero when the document definitions file does not exist, but currently it is always zero.

**Comment by ziemek** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/37.
