### ISSUE TITLE
Test helper convenience functions to build validation error messages

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#39]
Currently a user of the test helper module has to manually construct the text of the error messages they expect to encounter when document validation fails. This requires that the caller knows exactly what the expected error message content will be and it makes their test cases brittle. For the sake of convenience and keeping things DRY, include convenience functions to automatically format each of the built in validation error messages for use in specs.

For example, instead of

```
testHelper.verifyDocumentNotCreated(
  doc,
  'myDocType',
  [
    'item "provider" must not be empty',
    'item "accountId" must not be less than 1',
    'property "unrecognized-property3" is not supported'
  ],
  [ 'channel1', 'channel2' ]);
```

one could call

```
testHelper.verifyDocumentNotCreated(
  doc,
  'myDocType',
  [
    testHelper.formatNotEmptyMessage('provider'),
    testHelper.formatMinimumValueMessage('accountId', 1),
    testHelper.formatUnsupportedPropertyMessage('unrecognized-property3')
  ],
  [ 'channel1', 'channel2' ]);
```

**Comment by ziemek** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/41 and https://github.com/Kashoo/synctos/pull/46.
