### ISSUE TITLE
Tool to validate structure and semantics of a document definitions file

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#43]
Currently the `make-sync-function` script injects the specified document definitions file directly into the sync function template without any validation of its contents. Instead, it should verify the structure of the document definitions and output a warning for any violation it finds.

Examples of things to check for:
- if the document definitions are declared as a function, that function must return an object
- each document type includes a `channels` property
- channels in a document type's `channels` property are declared either as strings or arrays of strings
- a document type's `channels` property declares EITHER `write` OR `add`, `replace` and `remove`
- each document type includes a `typeFilter` that is a function
- if any of a document type's `allowAttachments`, `immutable`, `cannotDelete` or `cannotReplace` constraints are defined, they must have boolean values
- each validator in a document declares a supported validation `type`
- each of a validator's additional parameters conform to the validation type's expected input values (e.g. you can't assign a string value to a `float` property's `minimumValue` constraint)
- a validation parameter is assigned to a validation type that supports that parameter (e.g. you can't assign `regexPattern` to an `integer` property)
- an instance of a `customValidation` parameter is declared as a function
- etc.

**Comment by dkichler** [comment]
Finished off by #208
