### ISSUE TITLE
Upgrade development dependencies

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#52]
There are newer versions of several of the development dependencies used by synctos:
* [jshint](https://www.npmjs.com/package/jshint)
* [mocha](https://www.npmjs.com/package/mocha)
* [simple-mock](https://www.npmjs.com/package/simple-mock)

Update each dev dependency in `package.json` to ensure access to bug fixes and the latest features.

**Comment by dkichler** [comment]
This issue has been satisfied by #53
