### ISSUE TITLE
Access assignments should receive null when old document is deleted

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#54]
To simplify handling of dynamic access assignments when replacing an old document that was deleted, the user's access assignment functions (i.e. `users`, `roles` and `channels`) should receive an `oldDoc` parameter value of `null` rather than an object whose `_deleted` property is set to `true`. That way the user does not have to implement special handling for deleted vs. non-existant `oldDoc`. This is the same way that a deleted `oldDoc` is handled when passed to a `typeFilter` function.

See issue #24 for more info on access assignments.

**Comment by ziemek** [comment]
Fixed in https://github.com/Kashoo/synctos/pull/55.
