### ISSUE TITLE
Support dynamic assignment of roles to users

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#61]
Sync Gateway exposes the `role` function to sync functions, which allows roles to be assigned to users on the fly ([more info](http://developer.couchbase.com/documentation/mobile/current/guides/sync-gateway/sync-function-api-guide/index.html#role-username-rolename)). Add support for document definitions to supply role-assignment configuration that is applied after the user is authorized and the document's contents pass validation, but before channels are assigned (i.e. via the `channel` function).

For example (not to be considered final):

```
myDocType: {
  channels: ...,
  typeFilter: ...,
  propertyValidators: ...,
  accessAssignments: [
    {
      type: 'role',
      users: function(doc, oldDoc) {
        return doc.members;
      },
      roles: function(doc, oldDoc) {
        return doc.groups;
      }
    },
    {
      type: 'role',
      users: [ 'user1' ],
      roles: [ 'admins', 'power-users' ]
    }
  ]
},
```

Note that the `type` property is used to distinguish "role" assignments from "channel" assignments in the preceding example.

Related to #24 (Support dynamic assignment of channels to roles and users).

**Comment by dkichler** [comment]
Addressed by #64
