### ISSUE TITLE
Modular document definition files

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#66]
For a bucket/database with a large number of document types, it can be difficult to navigate through the document definition file to find the document type(s) you're looking for. Make document definitions modular by adding a macro that allows fragments to be imported directly into the main document definition file from secondary files.

For example:

```
{
    ...

    // A request/requisition for payment of an invoice
    paymentRequisition: importDocumentDefinitionFragment('payment-requisition-fragment.js'),

    // References the payment requisitions and payment attempts that were created for an invoice
    paymentRequisitionsReference: importDocumentDefinitionFragment('payment-requisitions-reference-fragment.js')

    ...
}
```

Imported fragments must have access to the functions and variables that are defined in the main document definitions file.

**Comment by dkichler** [comment]
Has been addressed by #67 and #68
