### ISSUE TITLE
Helper function to determine whether a document is missing or deleted

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#69]
Add a simple helper function (e.g. `isDocumentMissingOrDeleted`) that takes as input a document object and returns either `true` or `false` indicating whether that document is missing (i.e. it is `null` or `undefined`) or deleted (i.e. its "_deleted" property is `true`). This is useful for those cases where one wants to treat both cases (e.g. when handling the `oldDoc` parameter) as equivalent.

**Comment by cclark** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/71 which has now been merged.
