### ISSUE TITLE
New property validation type for type identifier properties

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#72]
Because a document's type is commonly specified via a property on the document itself (often called something like "type") in combination with a `typeFilter` value of `simpleTypeFilter`, add a new property validation type specifically for such type identifier properties (e.g. called "typeIdValidator") that is shorthand for the following:

```
{
  type: "string",
  required: true,
  mustNotBeEmpty: true,
  immutable: true
}
```

Related to #73.

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/74.
