### ISSUE TITLE
Include an implicit type property when a simple type filter is used

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#73]
The simple type filter (i.e. `simpleTypeFilter`) is a useful shorthand for documents that are identified exclusively by a type identifier property called "type". However, currently it is still necessary to explicitly include a property validator for the "type" property in the document's definition even when a simple type filter is used for that document type. Instead, when a simple type filter is specified for a document type and no explicit "type" property validator exists, implicitly assume the document type includes a property validator called "type" with the following constraints:

```
{
  type: "string",
  required: true,
  mustNotBeEmpty: true,
  immutable: true
}
```

Related to #72.

**Comment by dkichler** [comment]
Satisfied by #77
