### ISSUE TITLE
Decompose the sync function template

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#75]
The sync function template file ([etc/sync-function-template.js](https://github.com/Kashoo/synctos/blob/master/etc/sync-function-template.js)) has grown to a size that makes it increasingly difficult to navigate its embedded functions and variables. Group related components into external files/modules and import them into each generated sync function using a technique similar to that used in #67 for modular document definitions.

**Comment by dkichler** [comment]
Addressed by #83
