### ISSUE TITLE
Enum property validation type

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#78]
In some cases, it is necessary to limit a property to a certain set of acceptable values. Implement a new property validation type called "enum" for such cases. The list/set of acceptable values should allow both string and integer values.

For example (not to be considered final):

```
propertyValidators: {
  category: {
    type: 'enum',
    predefinedValues: [ 1, 2, 3, 'fruit', 'vegetable' ]
  }
}
```

**Comment by ziemek** [comment]
Addressed by https://github.com/Kashoo/synctos/pull/81.
