### ISSUE TITLE
Support minimum/maximum size constraint on hashtable validation type

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#79]
Just as the `array` property validation type allows one to constraint on the minimum and maximum length of array values (via the `minimumLength` and `maximumLength` constraints), allow one to specify the minimum and maximum number of elements that can be stored in a value that is declared with the `hashtable` validation type.

For example (not to be considered final):

```
propertyValidators: {
  accounts: {
    type: 'hashtable',
    required: true,
    minimumSize: 1,
    maximumSize: 2
  }
}
```

**Comment by ziemek** [comment]
Resolved by https://github.com/Kashoo/synctos/pull/82.
