### ISSUE TITLE
Decompose specifications file for sample document definitions

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#80]
The specs for the sample document definitions are all defined in a single file: `test/sample-sync-doc-definitions-spec.js`. The file's large size makes it unwieldy to navigate to the test cases that one might be interested in. Decompose the file such that the specification for each document definition is defined in its own file. Consider using npm [modules](https://docs.npmjs.com/getting-started/creating-node-modules) to accomplish this task.

**Comment by dkichler** [comment]
Addressed by #87
