### ISSUE TITLE
Conditional validation type

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#86]
# Feature Request

## Description

Currently each property or element can be defined with only one validation type (e.g. `string`, `integer`, `datetime`, etc.). However, there are cases where it may be beneficial to allow a value to be one of several types (e.g. a date as either an ISO 8601 date/time string or as a Unix timestamp) while still being able to set some constraints on them.

Add a new validation type (e.g. `conditional`) that selects one of several different validators to apply to a property or element based on some condition (specified as a function).

## Examples

```
propertyValidators: {
  date: {
    type: 'conditional',
    required: true,
    skipValidationWhenValueUnchangedStrict: true,
    validationCandidates: [
      {
        condition: function(doc, oldDoc, currentItemEntry, validationItemStack) {
          return typeof currentItemEntry.itemValue === 'string';
        },
        validator: {
          type: 'datetime',
          minimumValue: '1970-01-01T00:00Z'
        }
      },
      {
        condition: function(doc, oldDoc, currentItemEntry, validationItemStack) {
          return typeof currentItemEntry.itemValue === 'number';
        },
        validator: {
          type: 'integer',
          minimumValue: 0
        }
      }
    ]
  }
}
```

**Comment by dkichler** [comment]
Satisfied by #328
