### ISSUE TITLE
Document-wide constraints on file attachments

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#90]
Support document-level properties that limit
* the size, in bytes, of each individual file attachment associated with documents of that type (default: unlimited)
* the total size, in bytes, of all file attachments associated with a single document of that type (default: unlimited)
* the maximum number of file attachments that may be associated with a single document of that type (which would potentially render the existing `allowAttachments` property obsolete; default: unlimited)
* the content/MIME types that are allowed (default: unconstrained)
* the file extensions that are allowed (default: unconstrained)
* whether each attachment must have a corresponding property of the `attachmentReference` validation type (default: `false`)

Here is an example configuration (not to be considered final) that limits each attachment to 200 KB (i.e. 204,800 bytes), the total combined size of all attachments to 600 KB (i.e. 614,400 bytes), the maximum number of file attachments to 5, the supported content types to "text/plain" and "text/html", the file extensions that are supported to "txt" and "html" and that each attachment must have a corresponding `attachmentReference`:
```
foo: {
  typeFilter: ...,
  channels: ...,
  propertyValidators: ...,
  attachmentConstraints: {
    maximumIndividualSize: 204800,
    maximumTotalSize: 614400,
    maximumAttachmentCount: 5,
    supportedExtensions: [ 'txt', 'html' ],
    supportedContentTypes: [ 'text/plain', 'text/html' ],
    requireAttachmentReferences: true
  }
}
```

**Comment by dkichler** [comment]
Addressed by #91 and #92
