### ISSUE TITLE
Accept Date object for date/time constraint parameters

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#95]
Currently the minimum and maximum value parameters of the `date` and `datetime` validation types must be specified as [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) strings. Support the use of a `Date` object as well. For example:

```
propertyValidators: {
  myDate: {
    type: 'date',
    minimumValue: new Date(78234736),
    maximumValueExclusive: new Date(2017, 3, 14)
  }
}
```

The full list of `date` and `datetime` parameters that should support `Date` objects:
* `minimumValue`
* `minimumValueExclusive`
* `maximumValue`
* `maximumValueExclusive`

**Comment by skwoka** [comment]
I reviewed #99 and verified that `Date` object can now be used to specify min/max values for `date` and `datetime` validation types.
