### ISSUE TITLE
Support dynamic document constraints

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#97]
A number of constraints may be specified for a document type as static values. However, for greater flexibility, it should be possible to define these constraints dynamically, as a function. For example (not to be considered final):

```
{
  myDoc: {
    typeFilter: ...
    channels: ...
    propertyValidators: function(doc, oldDoc) {
      return ...;
    },
    immutable: function(doc, oldDoc) {
      return ...;
    },
    allowAttachments: function(doc, oldDoc) {
      return ...;
    }
  }
}
```

The full list of constraints for which to allow dynamic construction:
* `propertyValidators`
* `allowUnknownProperties`
* `immutable`
* `cannotReplace`
* `cannotDelete`
* `allowAttachments`
* `attachmentConstraints`:
    * `maximumAttachmentCount`
    * `maximumIndividualSize`
    * `maximumTotalSize`
    * `supportedExtensions`
    * `supportedContentTypes`
    * `requireAttachmentReferences`

Related to #94.

**Comment by dkichler** [comment]
Satisfied by #109 and #111
