### ISSUE TITLE
Final argument of custom validation constraint receives incorrect value

### ISSUE THREAD

**Issue by OldSneerJaw** [Kashoo/synctos#98]
The `customValidation` constraint accepts four arguments. The last argument is meant to contain a copy of the stack of validation items minus the item that is currently under evaluation. In other words, the first element of the array should contain the document object and the last element should contain the immediate parent of the item under evaluation.

However, it currently contains a copy of the stack of validation items minus all elements other than the item under evaluation. In other words, the array consists of a single element that contains the item under evaluation.

For example, with the following document definition

```javascript
{
  customValidationDoc: {
    typeFilter: simpleTypeFilter,
    channels: { write: 'write' },
    propertyValidators: {
      baseProp: {
        type: 'object',
        propertyValidators: {
          customValidationProp: {
            type: 'string',
            customValidation: function(doc, oldDoc, currentItemElement, validationItemStack) {
              return [ ];
            }
          }
        }
      }
    }
  }
}
```

the `validationItemStack` parameter should be an array representing the elements `[doc, baseProp]` but instead it is an array representing the elements `[customValidationProp]`.

**Comment by dkichler** [comment]
Addressed by #234
